export enum ReportType {
  TRANSACTION_SUMMARY = 'TRANSACTION_SUMMARY',
  BUDGET_PERFORMANCE = 'BUDGET_PERFORMANCE',
  EXPENSE_ANALYSIS = 'EXPENSE_ANALYSIS', 
  INCOME_ANALYSIS = 'INCOME_ANALYSIS',
  SAVINGS_PROGRESS = 'SAVINGS_PROGRESS',
  CUSTOM = 'CUSTOM'
}
