export enum NotificationType {
  BUDGET_THRESHOLD = 'BUDGET_THRESHOLD',
  TRANSACTION_ALERT = 'TRANSACTION_ALERT',
  ACCOUNT_ACTIVITY = 'ACCOUNT_ACTIVITY',
  ACCOUNT_BALANCE = 'ACCOUNT_BALANCE',
  WARNING = 'WARNING',
  ALERT = 'ALERT',
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
